services:
  arkeo-lcd-proxy:
    image: ghcr.io/arkeonetwork/arkeo-lcd-proxy:latest
    container_name: arkeo-lcd-proxy
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "1318:1318"
